# name: Lint

# on:
#   # Trigger the workflow on push or pull request,
#   # but only for the dev branch
#   push:
#     branches:
#       - dev
#   pull_request:
#     branches:
#       - dev

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: psf/black@stable
