name: CodeCov
on:
  # Trigger the workflow on push or pull request,
  # but only for the dev branch
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '2'

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Generate Report
      run: |
        pip install coverage
        pip install pytest
        coverage run -m unittest
        coverage report
